### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by JustHerby** [BSData/black-seas#1]
### Your Discord

Just_Herby#4314

### Additional information

Just started playing Black Seas and noticed a couple of issues with BSData/black-seas. I've fixed the things I noticed and added in all the national special rules to my local version, but I'd like to get it added to the github please.

Herby

**Comment by JustHerby** [comment]
Hi! Thank you, is there something else I need to do? All I got was an e-mail saying "/invite", should there be an actual link I can click?

**Comment by Mad-Spy** [comment]
No. I need to fix the automated workflows so that the slash command I used actually works.

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/2738921035)
:robot: Invited @JustHerby with **push** access. Invite can be accepted on https://github.com/BSData/black-seas/invitations
