### ISSUE TITLE
Wrong Points

### ISSUE THREAD

**Issue by AzureWight** [BSData/black-seas#3]
Several point issues:

Barque is 80 points not 70
Cutter renamed to Cutter (Large) for uniformity.
Galleon points from 90 to 130
Gun Ketch profile needs adding [S 1H-1L - - 20 Red 5 7 70]
4th Rate (Razeed) need changing to 200points

**Comment by JustHerby** [comment]
Cutter renames itself to Cutter (Large) when you add it to a Hold Fast! fleet, and the Galleon is only 130pts when using the "A Simpler Time" rules. The others I'll fix over the weekend. Thanks! :)

**Comment by JustHerby** [comment]
Also, Gun Ketch does have a profile, is it missing on a specific Navy?

**Comment by AzureWight** [comment]
It only appears to be present on generic fleet from CRB but I might be missing something again.

Also, HMS Indefatigable seems to not be showing within the GB list

**Comment by JustHerby** [comment]
Thanks, I definitely remember adding the Indie so I'll figure out what's happened!

Also, as an update, didn't get this done over the weekend as I promised because I moved house last week and my pc is still in pieces. I'll get this done as soon as I have a functioning pc to do it on.

**Comment by AzureWight** [comment]
Hi

No rush. Just thought I'd let you know. I have looked at the code and is does show "HMS Idefatigable" it just doesn't show in the list so I'm not sure which line of code is incorrect but something's stopping it from displaying 🙂
________________________________

**Comment by JustHerby** [comment]
I have *finally* got these sorted. Sorry for the ridiculous delay!
