### ISSUE TITLE
Russian ships wrong points

### ISSUE THREAD

**Issue by harisker** [BSData/black-seas#4]
**Describe the bug**
Based on the hold fast rules the russian ships are 10% cheaper
So for example a Russian frigate instead of 150 points should start with 150 - 10%*150 = 135 rounding down which is 130

**Comment by JustHerby** [comment]
Hi,

Thanks for the feedback :)

As the devs have admitted that the national special rules aren't balanced, I've made them optional in battlescribe. If you change the option under Additional Fleet Rules -> National Special Rules to Full National Special Rules, it'll reduce the ship points for each ship.

Also, you seem to be confusing ship points with points. The special rules for the Russian Navy just reduce their ship points, they don't make them cheaper. To continue your example, a Russian Fifth Rate with Full National Special Rules enabled goes from 36 ship points to 33.

**Comment by harisker** [comment]
The rule is "Reduce the initial Ship Points values of all Russian ships by 10% (rounding down)".
Why my example is wrong?
the initial points are 150
minus 10% is 135
round down is 130

and from 130 points you may start add upgrades and change crew.
