### ISSUE TITLE
Add Greek national rules

### ISSUE THREAD

**Issue by harisker** [BSData/black-seas#6]
Is it posible to add also the Greek national rules as it is in the below link from black seas group?

https://www.facebook.com/groups/WarlordGamesBlackSeasandBlackPowder/permalink/1215432855784293

Its only 2 characters, 2 ships and a restrict amount of line ships.

**Comment by JustHerby** [comment]
Once again, is there a non-facebook version of this? Otherwise will have to wait until I get access to the fb group.

**Comment by JustHerby** [comment]
I've now got access to the fb group, I'll add these as soon as I can.

**Comment by JustHerby** [comment]
After some thinking, I've changed my mind and will not be adding these rules, sorry.

Whilst undeniably cool they are just fan rules, and without some sort of blessing from the authors of the game I don't think it would be right to add them to Battlescribe, though if there are more fan rules for other nations it might be an idea to start a separate github repository for fan projects.

**Comment by harisker** [comment]
Thanks for liking them :)
I play test them a lot
